export const courses = [
  {
    id: 1,
    title: 'Fundamentos de React',
    category: 'Frontend',
    level: 'Inicial',
    duration: '6 horas',
    description: 'Componentes, props y estado para crear interfaces interactivas.',
    icon: '⚛',
    color: 'lavender',
    seats: 8,
  },
  {
    id: 2,
    title: 'Diseño con Bootstrap',
    category: 'Diseño',
    level: 'Inicial',
    duration: '4 horas',
    description: 'Layouts responsivos y componentes listos para usar.',
    icon: '◈',
    color: 'peach',
    seats: 5,
  },
  {
    id: 3,
    title: 'JavaScript moderno',
    category: 'Frontend',
    level: 'Intermedio',
    duration: '8 horas',
    description: 'Funciones, arrays y asincronía aplicados a proyectos reales.',
    icon: '{ }',
    color: 'mint',
    seats: 0,
  },
  {
    id: 4,
    title: 'Accesibilidad web',
    category: 'Diseño',
    level: 'Intermedio',
    duration: '5 horas',
    description: 'Interfaces que todas las personas pueden explorar y utilizar.',
    icon: '◎',
    color: 'sky',
    seats: 12,
  },
  {
    id: 5,
    title: 'APIs con Node.js',
    category: 'Backend',
    level: 'Intermedio',
    duration: '7 horas',
    description: 'Construye servicios y conecta tus aplicaciones con datos.',
    icon: '⌘',
    color: 'butter',
    seats: 3,
  },
  {
    id: 6,
    title: 'Bases de datos',
    category: 'Backend',
    level: 'Inicial',
    duration: '6 horas',
    description: 'Modela, consulta y organiza la información de tu app.',
    icon: '▤',
    color: 'rose',
    seats: 9,
  },
]
